// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace
{
    public static class GetDomain
    {
        public static Task<GetDomainResult> InvokeAsync(GetDomainArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDomainResult>("googleworkspace:index/getDomain:getDomain", args ?? new GetDomainArgs(), options.WithVersion());
    }


    public sealed class GetDomainArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The domain name of the customer.
        /// </summary>
        [Input("domainName", required: true)]
        public string DomainName { get; set; } = null!;

        public GetDomainArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDomainResult
    {
        /// <summary>
        /// Creation time of the domain. Expressed in Unix time format.
        /// </summary>
        public readonly int CreationTime;
        /// <summary>
        /// asps.list of domain alias objects.
        /// </summary>
        public readonly ImmutableArray<string> DomainAliases;
        /// <summary>
        /// The domain name of the customer.
        /// </summary>
        public readonly string DomainName;
        /// <summary>
        /// ETag of the resource.
        /// </summary>
        public readonly string Etag;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Indicates if the domain is a primary domain.
        /// </summary>
        public readonly bool IsPrimary;
        /// <summary>
        /// Indicates the verification state of a domain.
        /// </summary>
        public readonly bool Verified;

        [OutputConstructor]
        private GetDomainResult(
            int creationTime,

            ImmutableArray<string> domainAliases,

            string domainName,

            string etag,

            string id,

            bool isPrimary,

            bool verified)
        {
            CreationTime = creationTime;
            DomainAliases = domainAliases;
            DomainName = domainName;
            Etag = etag;
            Id = id;
            IsPrimary = isPrimary;
            Verified = verified;
        }
    }
}
