// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace
{
    public static class GetGroupMembers
    {
        public static Task<GetGroupMembersResult> InvokeAsync(GetGroupMembersArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetGroupMembersResult>("googleworkspace:index/getGroupMembers:getGroupMembers", args ?? new GetGroupMembersArgs(), options.WithVersion());
    }


    public sealed class GetGroupMembersArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Identifies the group in the API request. The value can be the group's email address, group alias, or the unique group ID.
        /// </summary>
        [Input("groupId", required: true)]
        public string GroupId { get; set; } = null!;

        public GetGroupMembersArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetGroupMembersResult
    {
        /// <summary>
        /// ETag of the resource.
        /// </summary>
        public readonly string Etag;
        /// <summary>
        /// Identifies the group in the API request. The value can be the group's email address, group alias, or the unique group ID.
        /// </summary>
        public readonly string GroupId;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The members of the group
        /// </summary>
        public readonly ImmutableArray<Outputs.GetGroupMembersMemberResult> Members;

        [OutputConstructor]
        private GetGroupMembersResult(
            string etag,

            string groupId,

            string id,

            ImmutableArray<Outputs.GetGroupMembersMemberResult> members)
        {
            Etag = etag;
            GroupId = groupId;
            Id = id;
            Members = members;
        }
    }
}
