// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Googleworkspace
{
    public static class GetPrivileges
    {
        public static Task<GetPrivilegesResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPrivilegesResult>("googleworkspace:index/getPrivileges:getPrivileges", InvokeArgs.Empty, options.WithVersion());
    }


    [OutputType]
    public sealed class GetPrivilegesResult
    {
        /// <summary>
        /// ETag of the resource.
        /// </summary>
        public readonly string Etag;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A list of Privilege resources. The API returns a tree-like structure with parent-child privileges, the provider flattens this list.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPrivilegesItemResult> Items;

        [OutputConstructor]
        private GetPrivilegesResult(
            string etag,

            string id,

            ImmutableArray<Outputs.GetPrivilegesItemResult> items)
        {
            Etag = etag;
            Id = id;
            Items = items;
        }
    }
}
