// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * ## Import
 *
 * ```sh
 *  $ pulumi import googleworkspace:role/roleAssignment:RoleAssignment dwight 12345678901234567
 * ```
 */
export class RoleAssignment extends pulumi.CustomResource {
    /**
     * Get an existing RoleAssignment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleAssignmentState, opts?: pulumi.CustomResourceOptions): RoleAssignment {
        return new RoleAssignment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'googleworkspace:role/roleAssignment:RoleAssignment';

    /**
     * Returns true if the given object is an instance of RoleAssignment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RoleAssignment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RoleAssignment.__pulumiType;
    }

    /**
     * The unique ID of the user this role is assigned to.
     */
    public readonly assignedTo!: pulumi.Output<string>;
    /**
     * ETag of the resource.
     */
    public /*out*/ readonly etag!: pulumi.Output<string>;
    /**
     * ID of this roleAssignment.
     */
    public /*out*/ readonly id!: pulumi.Output<string>;
    /**
     * If the role is restricted to an organization unit, this contains the ID for the organization unit the exercise of this role is restricted to.
     */
    public readonly orgUnitId!: pulumi.Output<string | undefined>;
    /**
     * The ID of the role that is assigned.
     */
    public readonly roleId!: pulumi.Output<string>;
    /**
     * The scope in which this role is assigned. Valid values are 'CUSTOMER' or 'ORG_UNIT' Defaults to `CUSTOMER`.
     */
    public readonly scopeType!: pulumi.Output<string | undefined>;

    /**
     * Create a RoleAssignment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleAssignmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleAssignmentArgs | RoleAssignmentState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleAssignmentState | undefined;
            inputs["assignedTo"] = state ? state.assignedTo : undefined;
            inputs["etag"] = state ? state.etag : undefined;
            inputs["id"] = state ? state.id : undefined;
            inputs["orgUnitId"] = state ? state.orgUnitId : undefined;
            inputs["roleId"] = state ? state.roleId : undefined;
            inputs["scopeType"] = state ? state.scopeType : undefined;
        } else {
            const args = argsOrState as RoleAssignmentArgs | undefined;
            if ((!args || args.assignedTo === undefined) && !opts.urn) {
                throw new Error("Missing required property 'assignedTo'");
            }
            if ((!args || args.roleId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            inputs["assignedTo"] = args ? args.assignedTo : undefined;
            inputs["orgUnitId"] = args ? args.orgUnitId : undefined;
            inputs["roleId"] = args ? args.roleId : undefined;
            inputs["scopeType"] = args ? args.scopeType : undefined;
            inputs["etag"] = undefined /*out*/;
            inputs["id"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(RoleAssignment.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RoleAssignment resources.
 */
export interface RoleAssignmentState {
    /**
     * The unique ID of the user this role is assigned to.
     */
    assignedTo?: pulumi.Input<string>;
    /**
     * ETag of the resource.
     */
    etag?: pulumi.Input<string>;
    /**
     * ID of this roleAssignment.
     */
    id?: pulumi.Input<string>;
    /**
     * If the role is restricted to an organization unit, this contains the ID for the organization unit the exercise of this role is restricted to.
     */
    orgUnitId?: pulumi.Input<string>;
    /**
     * The ID of the role that is assigned.
     */
    roleId?: pulumi.Input<string>;
    /**
     * The scope in which this role is assigned. Valid values are 'CUSTOMER' or 'ORG_UNIT' Defaults to `CUSTOMER`.
     */
    scopeType?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RoleAssignment resource.
 */
export interface RoleAssignmentArgs {
    /**
     * The unique ID of the user this role is assigned to.
     */
    assignedTo: pulumi.Input<string>;
    /**
     * If the role is restricted to an organization unit, this contains the ID for the organization unit the exercise of this role is restricted to.
     */
    orgUnitId?: pulumi.Input<string>;
    /**
     * The ID of the role that is assigned.
     */
    roleId: pulumi.Input<string>;
    /**
     * The scope in which this role is assigned. Valid values are 'CUSTOMER' or 'ORG_UNIT' Defaults to `CUSTOMER`.
     */
    scopeType?: pulumi.Input<string>;
}
