// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Role.Outputs
{

    [OutputType]
    public sealed class RolePrivilege
    {
        /// <summary>
        /// The name of the privilege.
        /// </summary>
        public readonly string PrivilegeName;
        /// <summary>
        /// The obfuscated ID of the service this privilege is for.
        /// </summary>
        public readonly string ServiceId;

        [OutputConstructor]
        private RolePrivilege(
            string privilegeName,

            string serviceId)
        {
            PrivilegeName = privilegeName;
            ServiceId = serviceId;
        }
    }
}
