// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class ChromePolicyPolicy
    {
        /// <summary>
        /// The full qualified name of the policy schema.
        /// </summary>
        public readonly string SchemaName;
        /// <summary>
        /// JSON encoded map that represents key/value pairs that correspond to the given schema.
        /// </summary>
        public readonly ImmutableDictionary<string, string> SchemaValues;

        [OutputConstructor]
        private ChromePolicyPolicy(
            string schemaName,

            ImmutableDictionary<string, string> schemaValues)
        {
            SchemaName = schemaName;
            SchemaValues = schemaValues;
        }
    }
}
