// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class GetUserSshPublicKeyResult
    {
        public readonly string ExpirationTimeUsec;
        public readonly string Fingerprint;
        public readonly string Key;

        [OutputConstructor]
        private GetUserSshPublicKeyResult(
            string expirationTimeUsec,

            string fingerprint,

            string key)
        {
            ExpirationTimeUsec = expirationTimeUsec;
            Fingerprint = fingerprint;
            Key = key;
        }
    }
}
