// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class GetUserAddressResult
    {
        public readonly string Country;
        public readonly string CountryCode;
        public readonly string CustomType;
        public readonly string ExtendedAddress;
        public readonly string Formatted;
        public readonly string Locality;
        public readonly string PoBox;
        public readonly string PostalCode;
        public readonly bool Primary;
        public readonly string Region;
        public readonly bool SourceIsStructured;
        public readonly string StreetAddress;
        public readonly string Type;

        [OutputConstructor]
        private GetUserAddressResult(
            string country,

            string countryCode,

            string customType,

            string extendedAddress,

            string formatted,

            string locality,

            string poBox,

            string postalCode,

            bool primary,

            string region,

            bool sourceIsStructured,

            string streetAddress,

            string type)
        {
            Country = country;
            CountryCode = countryCode;
            CustomType = customType;
            ExtendedAddress = extendedAddress;
            Formatted = formatted;
            Locality = locality;
            PoBox = poBox;
            PostalCode = postalCode;
            Primary = primary;
            Region = region;
            SourceIsStructured = sourceIsStructured;
            StreetAddress = streetAddress;
            Type = type;
        }
    }
}
