// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class GetUserNameResult
    {
        public readonly string FamilyName;
        public readonly string FullName;
        public readonly string GivenName;

        [OutputConstructor]
        private GetUserNameResult(
            string familyName,

            string fullName,

            string givenName)
        {
            FamilyName = familyName;
            FullName = fullName;
            GivenName = givenName;
        }
    }
}
