// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class GetUserLanguageResult
    {
        public readonly string CustomLanguage;
        public readonly string LanguageCode;

        [OutputConstructor]
        private GetUserLanguageResult(
            string customLanguage,

            string languageCode)
        {
            CustomLanguage = customLanguage;
            LanguageCode = languageCode;
        }
    }
}
