// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserSshPublicKey
    {
        /// <summary>
        /// An expiration time in microseconds since epoch.
        /// </summary>
        public readonly string? ExpirationTimeUsec;
        /// <summary>
        /// A SHA-256 fingerprint of the SSH public key.
        /// </summary>
        public readonly string? Fingerprint;
        /// <summary>
        /// An SSH public key.
        /// </summary>
        public readonly string Key;

        [OutputConstructor]
        private UserSshPublicKey(
            string? expirationTimeUsec,

            string? fingerprint,

            string key)
        {
            ExpirationTimeUsec = expirationTimeUsec;
            Fingerprint = fingerprint;
            Key = key;
        }
    }
}
