// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserEmail
    {
        /// <summary>
        /// The user's email address. Also serves as the email ID. This value can be the user's primary email address or an alias.
        /// </summary>
        public readonly string? Address;
        /// <summary>
        /// If the value of type is custom, this property contains the custom type string.
        /// </summary>
        public readonly string? CustomType;
        /// <summary>
        /// Indicates if this is the user's primary email. Only one entry can be marked as primary. Defaults to `false`.
        /// </summary>
        public readonly bool? Primary;
        /// <summary>
        /// The type of the email account. Acceptable values: `custom`, `home`, `other`, `work`.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private UserEmail(
            string? address,

            string? customType,

            bool? primary,

            string type)
        {
            Address = address;
            CustomType = customType;
            Primary = primary;
            Type = type;
        }
    }
}
