// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserWebsite
    {
        /// <summary>
        /// The custom type. Only used if the type is custom.
        /// </summary>
        public readonly string? CustomType;
        /// <summary>
        /// If this is user's primary website or not.
        /// </summary>
        public readonly bool? Primary;
        /// <summary>
        /// The type or purpose of the website. For example, a website could be labeled as home or blog. Alternatively, an entry can have a custom type Custom types must have a customType value. Acceptable values: `app_install_page`, `blog`, `custom`, `ftp` , `home`, `home_page`, `other`, `profile`, `reservations`, `resume`, `work`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The URL of the website.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private UserWebsite(
            string? customType,

            bool? primary,

            string type,

            string value)
        {
            CustomType = customType;
            Primary = primary;
            Type = type;
            Value = value;
        }
    }
}
