// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserIm
    {
        /// <summary>
        /// If the protocol value is custom_protocol, this property holds the custom protocol's string.
        /// </summary>
        public readonly string? CustomProtocol;
        /// <summary>
        /// If the IM type is custom, this property holds the custom type string.
        /// </summary>
        public readonly string? CustomType;
        /// <summary>
        /// The user's IM network ID.
        /// </summary>
        public readonly string? Im;
        /// <summary>
        /// If this is the user's primary IM. Only one entry in the IM list can have a value of true.
        /// </summary>
        public readonly bool? Primary;
        /// <summary>
        /// An IM protocol identifies the IM network. The value can be a custom network or the standard network. Acceptable values: `aim`, `custom_protocol`, `gtalk`, `icq`, `jabber`, `msn`, `net_meeting`, `qq`, `skype`, `yahoo`.
        /// </summary>
        public readonly string Protocol;
        /// <summary>
        /// Acceptable values: `custom`, `home`, `other`, `work`.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private UserIm(
            string? customProtocol,

            string? customType,

            string? im,

            bool? primary,

            string protocol,

            string type)
        {
            CustomProtocol = customProtocol;
            CustomType = customType;
            Im = im;
            Primary = primary;
            Protocol = protocol;
            Type = type;
        }
    }
}
