// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserPosixAccount
    {
        /// <summary>
        /// A POSIX account field identifier.
        /// </summary>
        public readonly string? AccountId;
        /// <summary>
        /// The GECOS (user information) for this account.
        /// </summary>
        public readonly string? Gecos;
        /// <summary>
        /// The default group ID.
        /// </summary>
        public readonly string? Gid;
        /// <summary>
        /// The path to the home directory for this account.
        /// </summary>
        public readonly string? HomeDirectory;
        /// <summary>
        /// The operating system type for this account. Acceptable values: `linux`, `unspecified`, `windows`.
        /// </summary>
        public readonly string? OperatingSystemType;
        /// <summary>
        /// If this is user's primary account within the SystemId.
        /// </summary>
        public readonly bool? Primary;
        /// <summary>
        /// The path to the login shell for this account.
        /// </summary>
        public readonly string? Shell;
        /// <summary>
        /// System identifier for which account Username or Uid apply to.
        /// </summary>
        public readonly string? SystemId;
        /// <summary>
        /// The POSIX compliant user ID.
        /// </summary>
        public readonly string? Uid;
        /// <summary>
        /// The username of the account.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private UserPosixAccount(
            string? accountId,

            string? gecos,

            string? gid,

            string? homeDirectory,

            string? operatingSystemType,

            bool? primary,

            string? shell,

            string? systemId,

            string? uid,

            string? username)
        {
            AccountId = accountId;
            Gecos = gecos;
            Gid = gid;
            HomeDirectory = homeDirectory;
            OperatingSystemType = operatingSystemType;
            Primary = primary;
            Shell = shell;
            SystemId = systemId;
            Uid = uid;
            Username = username;
        }
    }
}
