// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserExternalId
    {
        /// <summary>
        /// If the external ID type is custom, this property contains the custom value and must be set.
        /// </summary>
        public readonly string? CustomType;
        /// <summary>
        /// The type of external ID. If set to custom, customType must also be set. Acceptable values: `account`, `custom`, `customer`, `login_id`, `network`, `organization`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The value of the ID.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private UserExternalId(
            string? customType,

            string type,

            string value)
        {
            CustomType = customType;
            Type = type;
            Value = value;
        }
    }
}
