// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Outputs
{

    [OutputType]
    public sealed class UserAddress
    {
        /// <summary>
        /// Country
        /// </summary>
        public readonly string? Country;
        /// <summary>
        /// The country code. Uses the ISO 3166-1 standard.
        /// </summary>
        public readonly string? CountryCode;
        /// <summary>
        /// If the address type is custom, this property contains the custom value.
        /// </summary>
        public readonly string? CustomType;
        /// <summary>
        /// For extended addresses, such as an address that includes a sub-region.
        /// </summary>
        public readonly string? ExtendedAddress;
        /// <summary>
        /// A full and unstructured postal address. This is not synced with the structured address fields.
        /// </summary>
        public readonly string? Formatted;
        /// <summary>
        /// The town or city of the address.
        /// </summary>
        public readonly string? Locality;
        /// <summary>
        /// The post office box, if present.
        /// </summary>
        public readonly string? PoBox;
        /// <summary>
        /// The ZIP or postal code, if applicable.
        /// </summary>
        public readonly string? PostalCode;
        /// <summary>
        /// If this is the user's primary address. The addresses list may contain only one primary address.
        /// </summary>
        public readonly bool? Primary;
        /// <summary>
        /// The abbreviated province or state.
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// Indicates if the user-supplied address was formatted. Formatted addresses are not currently supported.
        /// </summary>
        public readonly bool? SourceIsStructured;
        /// <summary>
        /// The street address, such as 1600 Amphitheatre Parkway. Whitespace within the string is ignored; however, newlines are significant.
        /// </summary>
        public readonly string? StreetAddress;
        /// <summary>
        /// The address type. Acceptable values: `custom`, `home`, `other`, `work`.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private UserAddress(
            string? country,

            string? countryCode,

            string? customType,

            string? extendedAddress,

            string? formatted,

            string? locality,

            string? poBox,

            string? postalCode,

            bool? primary,

            string? region,

            bool? sourceIsStructured,

            string? streetAddress,

            string type)
        {
            Country = country;
            CountryCode = countryCode;
            CustomType = customType;
            ExtendedAddress = extendedAddress;
            Formatted = formatted;
            Locality = locality;
            PoBox = poBox;
            PostalCode = postalCode;
            Primary = primary;
            Region = region;
            SourceIsStructured = sourceIsStructured;
            StreetAddress = streetAddress;
            Type = type;
        }
    }
}
