// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package googleWorkspace

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDomainAlias(ctx *pulumi.Context, args *GetDomainAliasArgs, opts ...pulumi.InvokeOption) (*GetDomainAliasResult, error) {
	var rv GetDomainAliasResult
	err := ctx.Invoke("googleworkspace:index/getDomainAlias:getDomainAlias", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDomainAlias.
type GetDomainAliasArgs struct {
	// The domain alias name.
	DomainAliasName string `pulumi:"domainAliasName"`
}

// A collection of values returned by getDomainAlias.
type GetDomainAliasResult struct {
	// Creation time of the domain alias.
	CreationTime int `pulumi:"creationTime"`
	// The domain alias name.
	DomainAliasName string `pulumi:"domainAliasName"`
	// ETag of the resource.
	Etag string `pulumi:"etag"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The parent domain name that the domain alias is associated with. This can either be a primary or secondary domain name within a customer.
	ParentDomainName string `pulumi:"parentDomainName"`
	// Indicates the verification state of a domain alias.
	Verified bool `pulumi:"verified"`
}

func GetDomainAliasOutput(ctx *pulumi.Context, args GetDomainAliasOutputArgs, opts ...pulumi.InvokeOption) GetDomainAliasResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDomainAliasResult, error) {
			args := v.(GetDomainAliasArgs)
			r, err := GetDomainAlias(ctx, &args, opts...)
			return *r, err
		}).(GetDomainAliasResultOutput)
}

// A collection of arguments for invoking getDomainAlias.
type GetDomainAliasOutputArgs struct {
	// The domain alias name.
	DomainAliasName pulumi.StringInput `pulumi:"domainAliasName"`
}

func (GetDomainAliasOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainAliasArgs)(nil)).Elem()
}

// A collection of values returned by getDomainAlias.
type GetDomainAliasResultOutput struct{ *pulumi.OutputState }

func (GetDomainAliasResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainAliasResult)(nil)).Elem()
}

func (o GetDomainAliasResultOutput) ToGetDomainAliasResultOutput() GetDomainAliasResultOutput {
	return o
}

func (o GetDomainAliasResultOutput) ToGetDomainAliasResultOutputWithContext(ctx context.Context) GetDomainAliasResultOutput {
	return o
}

// Creation time of the domain alias.
func (o GetDomainAliasResultOutput) CreationTime() pulumi.IntOutput {
	return o.ApplyT(func(v GetDomainAliasResult) int { return v.CreationTime }).(pulumi.IntOutput)
}

// The domain alias name.
func (o GetDomainAliasResultOutput) DomainAliasName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainAliasResult) string { return v.DomainAliasName }).(pulumi.StringOutput)
}

// ETag of the resource.
func (o GetDomainAliasResultOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainAliasResult) string { return v.Etag }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o GetDomainAliasResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainAliasResult) string { return v.Id }).(pulumi.StringOutput)
}

// The parent domain name that the domain alias is associated with. This can either be a primary or secondary domain name within a customer.
func (o GetDomainAliasResultOutput) ParentDomainName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainAliasResult) string { return v.ParentDomainName }).(pulumi.StringOutput)
}

// Indicates the verification state of a domain alias.
func (o GetDomainAliasResultOutput) Verified() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainAliasResult) bool { return v.Verified }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainAliasResultOutput{})
}
