// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package googleWorkspace

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetGroupSettings(ctx *pulumi.Context, args *GetGroupSettingsArgs, opts ...pulumi.InvokeOption) (*GetGroupSettingsResult, error) {
	var rv GetGroupSettingsResult
	err := ctx.Invoke("googleworkspace:index/getGroupSettings:getGroupSettings", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGroupSettings.
type GetGroupSettingsArgs struct {
	// The group's email address.
	Email string `pulumi:"email"`
}

// A collection of values returned by getGroupSettings.
type GetGroupSettingsResult struct {
	// Identifies whether members external to your organization can join the group. If true, Google Workspace users external to your organization can become members of this group. If false, users not belonging to the organization are not allowed to become members of this group.
	AllowExternalMembers bool `pulumi:"allowExternalMembers"`
	// Allows posting from web. If true, allows any member to post to the group forum. If false, Members only use Gmail to communicate with the group.
	AllowWebPosting bool `pulumi:"allowWebPosting"`
	// Allows the group to be archived only. If true, Group is archived and the group is inactive. New messages to this group are rejected. The older archived messages are browsable and searchable. If true, the `whoCanPostMessage` property is set to `NONE_CAN_POST`. If reverted from true to false, `whoCanPostMessage` is set to `ALL_MANAGERS_CAN_POST`. If false, The group is active and can receive messages. When false, updating `whoCanPostMessage` to `NONE_CAN_POST`, results in an error.
	ArchiveOnly bool `pulumi:"archiveOnly"`
	// Set the content of custom footer text. The maximum number of characters is 1,000.
	CustomFooterText string `pulumi:"customFooterText"`
	// An email address used when replying to a message if the `replyTo` property is set to `REPLY_TO_CUSTOM`. This address is defined by an account administrator. When the group's `replyTo` property is set to `REPLY_TO_CUSTOM`, the `customReplyTo` property holds a custom email address used when replying to a message, the `customReplyTo` property must have a text value or an error is returned.
	CustomReplyTo string `pulumi:"customReplyTo"`
	// Specifies whether the group has a custom role that's included in one of the settings being merged.
	CustomRolesEnabledForSettingsToBeMerged bool `pulumi:"customRolesEnabledForSettingsToBeMerged"`
	// When a message is rejected, this is text for the rejection notification sent to the message's author. By default, this property is empty and has no value in the API's response body. The maximum notification text size is 10,000 characters. Requires `sendMessageDenyNotification` property to be true.
	DefaultMessageDenyNotificationText string `pulumi:"defaultMessageDenyNotificationText"`
	// Description of the group. The maximum group description is no more than 300 characters.
	Description string `pulumi:"description"`
	// The group's email address.
	Email string `pulumi:"email"`
	// Specifies whether a collaborative inbox will remain turned on for the group.
	EnableCollaborativeInbox bool `pulumi:"enableCollaborativeInbox"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// Whether to include custom footer.
	IncludeCustomFooter bool `pulumi:"includeCustomFooter"`
	// Enables the group to be included in the Global Address List. If true, the group is included in the Global Address List. If false, it is not included in the Global Address List.
	IncludeInGlobalAddressList bool `pulumi:"includeInGlobalAddressList"`
	// Allows the Group contents to be archived. If true, archive messages sent to the group. If false, Do not keep an archive of messages sent to this group. If false, previously archived messages remain in the archive.
	IsArchived bool `pulumi:"isArchived"`
	// Enables members to post messages as the group. If true, group member can post messages using the group's email address instead of their own email address. Message appear to originate from the group itself. Any message moderation settings on individual users or new members do not apply to posts made on behalf of the group. If false, members can not post in behalf of the group's email address.
	MembersCanPostAsTheGroup bool `pulumi:"membersCanPostAsTheGroup"`
	// Moderation level of incoming messages. Possible values are: `MODERATE_ALL_MESSAGES`: All messages are sent to the group owner's email address for approval. If approved, the message is sent to the group. `MODERATE_NON_MEMBERS`: All messages from non group members are sent to the group owner's email address for approval. If approved, the message is sent to the group. `MODERATE_NEW_MEMBERS`: All messages from new members are sent to the group owner's email address for approval. If approved, the message is sent to the group. `MODERATE_NONE`: No moderator approval is required. Messages are delivered directly to the group.Note: When the `whoCanPostMessage` is set to `ANYONE_CAN_POST`, we recommend the `messageModerationLevel` be set to `MODERATE_NON_MEMBERS` to protect the group from possible spam.When `memberCanPostAsTheGroup` is true, any message moderation settings on individual users or new members will not apply to posts made on behalf of the group.
	MessageModerationLevel string `pulumi:"messageModerationLevel"`
	// Name of the group, which has a maximum size of 75 characters.
	Name string `pulumi:"name"`
	// The primary language for group. For a group's primary language use the language tags from the Google Workspace languages found at Google Workspace Email Settings API Email Language Tags.
	PrimaryLanguage string `pulumi:"primaryLanguage"`
	// Specifies who receives the default reply. Possible values are: `REPLY_TO_CUSTOM`: For replies to messages, use the group's custom email address. When set to `REPLY_TO_CUSTOM`, the `customReplyTo` property holds the custom email address used when replying to a message, the customReplyTo property must have a value. Otherwise an error is returned. `REPLY_TO_SENDER`: The reply sent to author of message. `REPLY_TO_LIST`: This reply message is sent to the group. `REPLY_TO_OWNER`: The reply is sent to the owner(s) of the group. This does not include the group's managers. `REPLY_TO_IGNORE`: Group users individually decide where the message reply is sent. `REPLY_TO_MANAGERS`: This reply message is sent to the group's managers, which includes all managers and the group owner.
	ReplyTo string `pulumi:"replyTo"`
	// Allows a member to be notified if the member's message to the group is denied by the group owner. If true, when a message is rejected, send the deny message notification to the message author. The `defaultMessageDenyNotificationText` property is dependent on the `sendMessageDenyNotification` property being true. If false, when a message is rejected, no notification is sent.
	SendMessageDenyNotification bool `pulumi:"sendMessageDenyNotification"`
	// Specifies moderation levels for messages detected as spam. Possible values are: `ALLOW`: Post the message to the group. `MODERATE`: Send the message to the moderation queue. This is the default. `SILENTLY_MODERATE`: Send the message to the moderation queue, but do not send notification to moderators. `REJECT`: Immediately reject the message.
	SpamModerationLevel string `pulumi:"spamModerationLevel"`
	// Specifies who can moderate metadata. Possible values are: `ALL_MEMBERS`, `OWNERS_AND_MANAGERS`, `MANAGERS_ONLY`, `OWNERS_ONLY`, `NONE`
	WhoCanAssistContent string `pulumi:"whoCanAssistContent"`
	// Permission to contact owner of the group via web UI. Possible values are: `ALL_IN_DOMAIN_CAN_CONTACT`, `ALL_MANAGERS_CAN_CONTACT`, `ALL_MEMBERS_CAN_CONTACT`, `ANYONE_CAN_CONTACT`
	WhoCanContactOwner string `pulumi:"whoCanContactOwner"`
	// Specifies the set of users for whom this group is discoverable. Possible values are: `ANYONE_CAN_DISCOVER`, `ALL_IN_DOMAIN_CAN_DISCOVER`, `ALL_MEMBERS_CAN_DISCOVER`
	WhoCanDiscoverGroup string `pulumi:"whoCanDiscoverGroup"`
	// Permission to join group. Possible values are: `ANYONE_CAN_JOIN`: Any Internet user, both inside and outside your domain, can join the group. `ALL_IN_DOMAIN_CAN_JOIN`: Anyone in the account domain can join. This includes accounts with multiple domains. `INVITED_CAN_JOIN`: Candidates for membership can be invited to join. `CAN_REQUEST_TO_JOIN`: Non members can request an invitation to join.
	WhoCanJoin string `pulumi:"whoCanJoin"`
	// Permission to leave the group. Possible values are: `ALL_MANAGERS_CAN_LEAVE`, `ALL_MEMBERS_CAN_LEAVE`, `NONE_CAN_LEAVE`
	WhoCanLeaveGroup string `pulumi:"whoCanLeaveGroup"`
	// Specifies who can moderate content. Possible values are: `ALL_MEMBERS`, `OWNERS_AND_MANAGERS`, `OWNERS_ONLY`, `NONE`
	WhoCanModerateContent string `pulumi:"whoCanModerateContent"`
	// Specifies who can manage members. Possible values are: `ALL_MEMBERS`, `OWNERS_AND_MANAGERS`, `OWNERS_ONLY`, `NONE`
	WhoCanModerateMembers string `pulumi:"whoCanModerateMembers"`
	// Permissions to post messages. Possible values are: `NONE_CAN_POST`: The group is disabled and archived. No one can post a message to this group. * When archiveOnly is false, updating whoCanPostMessage to NONE*CAN*POST, results in an error. * If archiveOnly is reverted from true to false, whoCanPostMessages is set to ALL*MANAGERS*CAN_POST. `ALL_MANAGERS_CAN_POST`: Managers, including group owners, can post messages. `ALL_MEMBERS_CAN_POST`: Any group member can post a message. `ALL_OWNERS_CAN_POST`: Only group owners can post a message. `ALL_IN_DOMAIN_CAN_POST`: Anyone in the account can post a message. `ANYONE_CAN_POST`: Any Internet user who outside your account can access your Google Groups service and post a message. *Note: When `whoCanPostMessage` is set to `ANYONE_CAN_POST`, we recommend the`messageModerationLevel` be set to `MODERATE_NON_MEMBERS` to protect the group from possible spam. Users not belonging to the organization are not allowed to become members of this group.
	WhoCanPostMessage string `pulumi:"whoCanPostMessage"`
	// Permissions to view group messages. Possible values are: `ANYONE_CAN_VIEW`: Any Internet user can view the group's messages. `ALL_IN_DOMAIN_CAN_VIEW`: Anyone in your account can view this group's messages. `ALL_MEMBERS_CAN_VIEW`: All group members can view the group's messages. `ALL_MANAGERS_CAN_VIEW`: Any group manager can view this group's messages.
	WhoCanViewGroup string `pulumi:"whoCanViewGroup"`
	// Permissions to view membership. Possible values are: `ALL_IN_DOMAIN_CAN_VIEW`: Anyone in the account can view the group members list. If a group already has external members, those members can still send email to this group. `ALL_MEMBERS_CAN_VIEW`: The group members can view the group members list. `ALL_MANAGERS_CAN_VIEW`: The group managers can view group members list.
	WhoCanViewMembership string `pulumi:"whoCanViewMembership"`
}

func GetGroupSettingsOutput(ctx *pulumi.Context, args GetGroupSettingsOutputArgs, opts ...pulumi.InvokeOption) GetGroupSettingsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetGroupSettingsResult, error) {
			args := v.(GetGroupSettingsArgs)
			r, err := GetGroupSettings(ctx, &args, opts...)
			return *r, err
		}).(GetGroupSettingsResultOutput)
}

// A collection of arguments for invoking getGroupSettings.
type GetGroupSettingsOutputArgs struct {
	// The group's email address.
	Email pulumi.StringInput `pulumi:"email"`
}

func (GetGroupSettingsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGroupSettingsArgs)(nil)).Elem()
}

// A collection of values returned by getGroupSettings.
type GetGroupSettingsResultOutput struct{ *pulumi.OutputState }

func (GetGroupSettingsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGroupSettingsResult)(nil)).Elem()
}

func (o GetGroupSettingsResultOutput) ToGetGroupSettingsResultOutput() GetGroupSettingsResultOutput {
	return o
}

func (o GetGroupSettingsResultOutput) ToGetGroupSettingsResultOutputWithContext(ctx context.Context) GetGroupSettingsResultOutput {
	return o
}

// Identifies whether members external to your organization can join the group. If true, Google Workspace users external to your organization can become members of this group. If false, users not belonging to the organization are not allowed to become members of this group.
func (o GetGroupSettingsResultOutput) AllowExternalMembers() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.AllowExternalMembers }).(pulumi.BoolOutput)
}

// Allows posting from web. If true, allows any member to post to the group forum. If false, Members only use Gmail to communicate with the group.
func (o GetGroupSettingsResultOutput) AllowWebPosting() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.AllowWebPosting }).(pulumi.BoolOutput)
}

// Allows the group to be archived only. If true, Group is archived and the group is inactive. New messages to this group are rejected. The older archived messages are browsable and searchable. If true, the `whoCanPostMessage` property is set to `NONE_CAN_POST`. If reverted from true to false, `whoCanPostMessage` is set to `ALL_MANAGERS_CAN_POST`. If false, The group is active and can receive messages. When false, updating `whoCanPostMessage` to `NONE_CAN_POST`, results in an error.
func (o GetGroupSettingsResultOutput) ArchiveOnly() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.ArchiveOnly }).(pulumi.BoolOutput)
}

// Set the content of custom footer text. The maximum number of characters is 1,000.
func (o GetGroupSettingsResultOutput) CustomFooterText() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.CustomFooterText }).(pulumi.StringOutput)
}

// An email address used when replying to a message if the `replyTo` property is set to `REPLY_TO_CUSTOM`. This address is defined by an account administrator. When the group's `replyTo` property is set to `REPLY_TO_CUSTOM`, the `customReplyTo` property holds a custom email address used when replying to a message, the `customReplyTo` property must have a text value or an error is returned.
func (o GetGroupSettingsResultOutput) CustomReplyTo() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.CustomReplyTo }).(pulumi.StringOutput)
}

// Specifies whether the group has a custom role that's included in one of the settings being merged.
func (o GetGroupSettingsResultOutput) CustomRolesEnabledForSettingsToBeMerged() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.CustomRolesEnabledForSettingsToBeMerged }).(pulumi.BoolOutput)
}

// When a message is rejected, this is text for the rejection notification sent to the message's author. By default, this property is empty and has no value in the API's response body. The maximum notification text size is 10,000 characters. Requires `sendMessageDenyNotification` property to be true.
func (o GetGroupSettingsResultOutput) DefaultMessageDenyNotificationText() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.DefaultMessageDenyNotificationText }).(pulumi.StringOutput)
}

// Description of the group. The maximum group description is no more than 300 characters.
func (o GetGroupSettingsResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.Description }).(pulumi.StringOutput)
}

// The group's email address.
func (o GetGroupSettingsResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.Email }).(pulumi.StringOutput)
}

// Specifies whether a collaborative inbox will remain turned on for the group.
func (o GetGroupSettingsResultOutput) EnableCollaborativeInbox() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.EnableCollaborativeInbox }).(pulumi.BoolOutput)
}

// The ID of this resource.
func (o GetGroupSettingsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Whether to include custom footer.
func (o GetGroupSettingsResultOutput) IncludeCustomFooter() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.IncludeCustomFooter }).(pulumi.BoolOutput)
}

// Enables the group to be included in the Global Address List. If true, the group is included in the Global Address List. If false, it is not included in the Global Address List.
func (o GetGroupSettingsResultOutput) IncludeInGlobalAddressList() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.IncludeInGlobalAddressList }).(pulumi.BoolOutput)
}

// Allows the Group contents to be archived. If true, archive messages sent to the group. If false, Do not keep an archive of messages sent to this group. If false, previously archived messages remain in the archive.
func (o GetGroupSettingsResultOutput) IsArchived() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.IsArchived }).(pulumi.BoolOutput)
}

// Enables members to post messages as the group. If true, group member can post messages using the group's email address instead of their own email address. Message appear to originate from the group itself. Any message moderation settings on individual users or new members do not apply to posts made on behalf of the group. If false, members can not post in behalf of the group's email address.
func (o GetGroupSettingsResultOutput) MembersCanPostAsTheGroup() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.MembersCanPostAsTheGroup }).(pulumi.BoolOutput)
}

// Moderation level of incoming messages. Possible values are: `MODERATE_ALL_MESSAGES`: All messages are sent to the group owner's email address for approval. If approved, the message is sent to the group. `MODERATE_NON_MEMBERS`: All messages from non group members are sent to the group owner's email address for approval. If approved, the message is sent to the group. `MODERATE_NEW_MEMBERS`: All messages from new members are sent to the group owner's email address for approval. If approved, the message is sent to the group. `MODERATE_NONE`: No moderator approval is required. Messages are delivered directly to the group.Note: When the `whoCanPostMessage` is set to `ANYONE_CAN_POST`, we recommend the `messageModerationLevel` be set to `MODERATE_NON_MEMBERS` to protect the group from possible spam.When `memberCanPostAsTheGroup` is true, any message moderation settings on individual users or new members will not apply to posts made on behalf of the group.
func (o GetGroupSettingsResultOutput) MessageModerationLevel() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.MessageModerationLevel }).(pulumi.StringOutput)
}

// Name of the group, which has a maximum size of 75 characters.
func (o GetGroupSettingsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.Name }).(pulumi.StringOutput)
}

// The primary language for group. For a group's primary language use the language tags from the Google Workspace languages found at Google Workspace Email Settings API Email Language Tags.
func (o GetGroupSettingsResultOutput) PrimaryLanguage() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.PrimaryLanguage }).(pulumi.StringOutput)
}

// Specifies who receives the default reply. Possible values are: `REPLY_TO_CUSTOM`: For replies to messages, use the group's custom email address. When set to `REPLY_TO_CUSTOM`, the `customReplyTo` property holds the custom email address used when replying to a message, the customReplyTo property must have a value. Otherwise an error is returned. `REPLY_TO_SENDER`: The reply sent to author of message. `REPLY_TO_LIST`: This reply message is sent to the group. `REPLY_TO_OWNER`: The reply is sent to the owner(s) of the group. This does not include the group's managers. `REPLY_TO_IGNORE`: Group users individually decide where the message reply is sent. `REPLY_TO_MANAGERS`: This reply message is sent to the group's managers, which includes all managers and the group owner.
func (o GetGroupSettingsResultOutput) ReplyTo() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.ReplyTo }).(pulumi.StringOutput)
}

// Allows a member to be notified if the member's message to the group is denied by the group owner. If true, when a message is rejected, send the deny message notification to the message author. The `defaultMessageDenyNotificationText` property is dependent on the `sendMessageDenyNotification` property being true. If false, when a message is rejected, no notification is sent.
func (o GetGroupSettingsResultOutput) SendMessageDenyNotification() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) bool { return v.SendMessageDenyNotification }).(pulumi.BoolOutput)
}

// Specifies moderation levels for messages detected as spam. Possible values are: `ALLOW`: Post the message to the group. `MODERATE`: Send the message to the moderation queue. This is the default. `SILENTLY_MODERATE`: Send the message to the moderation queue, but do not send notification to moderators. `REJECT`: Immediately reject the message.
func (o GetGroupSettingsResultOutput) SpamModerationLevel() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.SpamModerationLevel }).(pulumi.StringOutput)
}

// Specifies who can moderate metadata. Possible values are: `ALL_MEMBERS`, `OWNERS_AND_MANAGERS`, `MANAGERS_ONLY`, `OWNERS_ONLY`, `NONE`
func (o GetGroupSettingsResultOutput) WhoCanAssistContent() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanAssistContent }).(pulumi.StringOutput)
}

// Permission to contact owner of the group via web UI. Possible values are: `ALL_IN_DOMAIN_CAN_CONTACT`, `ALL_MANAGERS_CAN_CONTACT`, `ALL_MEMBERS_CAN_CONTACT`, `ANYONE_CAN_CONTACT`
func (o GetGroupSettingsResultOutput) WhoCanContactOwner() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanContactOwner }).(pulumi.StringOutput)
}

// Specifies the set of users for whom this group is discoverable. Possible values are: `ANYONE_CAN_DISCOVER`, `ALL_IN_DOMAIN_CAN_DISCOVER`, `ALL_MEMBERS_CAN_DISCOVER`
func (o GetGroupSettingsResultOutput) WhoCanDiscoverGroup() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanDiscoverGroup }).(pulumi.StringOutput)
}

// Permission to join group. Possible values are: `ANYONE_CAN_JOIN`: Any Internet user, both inside and outside your domain, can join the group. `ALL_IN_DOMAIN_CAN_JOIN`: Anyone in the account domain can join. This includes accounts with multiple domains. `INVITED_CAN_JOIN`: Candidates for membership can be invited to join. `CAN_REQUEST_TO_JOIN`: Non members can request an invitation to join.
func (o GetGroupSettingsResultOutput) WhoCanJoin() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanJoin }).(pulumi.StringOutput)
}

// Permission to leave the group. Possible values are: `ALL_MANAGERS_CAN_LEAVE`, `ALL_MEMBERS_CAN_LEAVE`, `NONE_CAN_LEAVE`
func (o GetGroupSettingsResultOutput) WhoCanLeaveGroup() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanLeaveGroup }).(pulumi.StringOutput)
}

// Specifies who can moderate content. Possible values are: `ALL_MEMBERS`, `OWNERS_AND_MANAGERS`, `OWNERS_ONLY`, `NONE`
func (o GetGroupSettingsResultOutput) WhoCanModerateContent() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanModerateContent }).(pulumi.StringOutput)
}

// Specifies who can manage members. Possible values are: `ALL_MEMBERS`, `OWNERS_AND_MANAGERS`, `OWNERS_ONLY`, `NONE`
func (o GetGroupSettingsResultOutput) WhoCanModerateMembers() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanModerateMembers }).(pulumi.StringOutput)
}

// Permissions to post messages. Possible values are: `NONE_CAN_POST`: The group is disabled and archived. No one can post a message to this group. * When archiveOnly is false, updating whoCanPostMessage to NONE*CAN*POST, results in an error. * If archiveOnly is reverted from true to false, whoCanPostMessages is set to ALL*MANAGERS*CAN_POST. `ALL_MANAGERS_CAN_POST`: Managers, including group owners, can post messages. `ALL_MEMBERS_CAN_POST`: Any group member can post a message. `ALL_OWNERS_CAN_POST`: Only group owners can post a message. `ALL_IN_DOMAIN_CAN_POST`: Anyone in the account can post a message. `ANYONE_CAN_POST`: Any Internet user who outside your account can access your Google Groups service and post a message. *Note: When `whoCanPostMessage` is set to `ANYONE_CAN_POST`, we recommend the`messageModerationLevel` be set to `MODERATE_NON_MEMBERS` to protect the group from possible spam. Users not belonging to the organization are not allowed to become members of this group.
func (o GetGroupSettingsResultOutput) WhoCanPostMessage() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanPostMessage }).(pulumi.StringOutput)
}

// Permissions to view group messages. Possible values are: `ANYONE_CAN_VIEW`: Any Internet user can view the group's messages. `ALL_IN_DOMAIN_CAN_VIEW`: Anyone in your account can view this group's messages. `ALL_MEMBERS_CAN_VIEW`: All group members can view the group's messages. `ALL_MANAGERS_CAN_VIEW`: Any group manager can view this group's messages.
func (o GetGroupSettingsResultOutput) WhoCanViewGroup() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanViewGroup }).(pulumi.StringOutput)
}

// Permissions to view membership. Possible values are: `ALL_IN_DOMAIN_CAN_VIEW`: Anyone in the account can view the group members list. If a group already has external members, those members can still send email to this group. `ALL_MEMBERS_CAN_VIEW`: The group members can view the group members list. `ALL_MANAGERS_CAN_VIEW`: The group managers can view group members list.
func (o GetGroupSettingsResultOutput) WhoCanViewMembership() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupSettingsResult) string { return v.WhoCanViewMembership }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetGroupSettingsResultOutput{})
}
