// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./group";
export * from "./groupMember";
export * from "./groupMembers";
export * from "./groupSettings";

// Import resources to register:
import { Group } from "./group";
import { GroupMember } from "./groupMember";
import { GroupMembers } from "./groupMembers";
import { GroupSettings } from "./groupSettings";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "googleworkspace:group/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "googleworkspace:group/groupMember:GroupMember":
                return new GroupMember(name, <any>undefined, { urn })
            case "googleworkspace:group/groupMembers:GroupMembers":
                return new GroupMembers(name, <any>undefined, { urn })
            case "googleworkspace:group/groupSettings:GroupSettings":
                return new GroupSettings(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("googleWorkspace", "group/group", _module)
pulumi.runtime.registerResourceModule("googleWorkspace", "group/groupMember", _module)
pulumi.runtime.registerResourceModule("googleWorkspace", "group/groupMembers", _module)
pulumi.runtime.registerResourceModule("googleWorkspace", "group/groupSettings", _module)
