# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'RolePrivilegeArgs',
]

@pulumi.input_type
class RolePrivilegeArgs:
    def __init__(__self__, *,
                 privilege_name: pulumi.Input[str],
                 service_id: pulumi.Input[str]):
        """
        :param pulumi.Input[str] privilege_name: The name of the privilege.
        :param pulumi.Input[str] service_id: The obfuscated ID of the service this privilege is for.
        """
        pulumi.set(__self__, "privilege_name", privilege_name)
        pulumi.set(__self__, "service_id", service_id)

    @property
    @pulumi.getter(name="privilegeName")
    def privilege_name(self) -> pulumi.Input[str]:
        """
        The name of the privilege.
        """
        return pulumi.get(self, "privilege_name")

    @privilege_name.setter
    def privilege_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "privilege_name", value)

    @property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> pulumi.Input[str]:
        """
        The obfuscated ID of the service this privilege is for.
        """
        return pulumi.get(self, "service_id")

    @service_id.setter
    def service_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "service_id", value)


