// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./domain";
export * from "./domainAlias";

// Import resources to register:
import { Domain } from "./domain";
import { DomainAlias } from "./domainAlias";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "googleworkspace:domain/domain:Domain":
                return new Domain(name, <any>undefined, { urn })
            case "googleworkspace:domain/domainAlias:DomainAlias":
                return new DomainAlias(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("googleWorkspace", "domain/domain", _module)
pulumi.runtime.registerResourceModule("googleWorkspace", "domain/domainAlias", _module)
