// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Inputs
{

    public sealed class ChromePolicyPolicyGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The full qualified name of the policy schema.
        /// </summary>
        [Input("schemaName", required: true)]
        public Input<string> SchemaName { get; set; } = null!;

        [Input("schemaValues", required: true)]
        private InputMap<string>? _schemaValues;

        /// <summary>
        /// JSON encoded map that represents key/value pairs that correspond to the given schema.
        /// </summary>
        public InputMap<string> SchemaValues
        {
            get => _schemaValues ?? (_schemaValues = new InputMap<string>());
            set => _schemaValues = value;
        }

        public ChromePolicyPolicyGetArgs()
        {
        }
    }
}
