// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Inputs
{

    public sealed class UserLocationGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Textual location. This is most useful for display purposes to concisely describe the location. For example, Mountain View, CA or Near Seattle.
        /// </summary>
        [Input("area")]
        public Input<string>? Area { get; set; }

        /// <summary>
        /// Building identifier.
        /// </summary>
        [Input("buildingId")]
        public Input<string>? BuildingId { get; set; }

        /// <summary>
        /// If the location type is custom, this property contains the custom value.
        /// </summary>
        [Input("customType")]
        public Input<string>? CustomType { get; set; }

        /// <summary>
        /// Most specific textual code of individual desk location.
        /// </summary>
        [Input("deskCode")]
        public Input<string>? DeskCode { get; set; }

        /// <summary>
        /// Floor name/number.
        /// </summary>
        [Input("floorName")]
        public Input<string>? FloorName { get; set; }

        /// <summary>
        /// Floor section. More specific location within the floor. For example, if a floor is divided into sections A, B, and C, this field would identify one of those values.
        /// </summary>
        [Input("floorSection")]
        public Input<string>? FloorSection { get; set; }

        /// <summary>
        /// The location type. Acceptable values: `custom`, `default`, `desk`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public UserLocationGetArgs()
        {
        }
    }
}
