// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Inputs
{

    public sealed class UserLanguageArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Other language. A user can provide their own language name if there is no corresponding Google III language code. If this is set, LanguageCode can't be set.
        /// </summary>
        [Input("customLanguage")]
        public Input<string>? CustomLanguage { get; set; }

        /// <summary>
        /// Language Code. Should be used for storing Google III LanguageCode string representation for language. Illegal values cause SchemaException.
        /// </summary>
        [Input("languageCode")]
        public Input<string>? LanguageCode { get; set; }

        public UserLanguageArgs()
        {
        }
    }
}
