// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Inputs
{

    public sealed class UserOrganizationArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The cost center of the user's organization.
        /// </summary>
        [Input("costCenter")]
        public Input<string>? CostCenter { get; set; }

        /// <summary>
        /// If the value of type is custom, this property contains the custom value.
        /// </summary>
        [Input("customType")]
        public Input<string>? CustomType { get; set; }

        /// <summary>
        /// Specifies the department within the organization, such as sales or engineering.
        /// </summary>
        [Input("department")]
        public Input<string>? Department { get; set; }

        /// <summary>
        /// The description of the organization.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The domain the organization belongs to.
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        /// <summary>
        /// The full-time equivalent millipercent within the organization (100000 = 100%)
        /// </summary>
        [Input("fullTimeEquivalent")]
        public Input<int>? FullTimeEquivalent { get; set; }

        /// <summary>
        /// The physical location of the organization. This does not need to be a fully qualified address.
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// The name of the organization.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Indicates if this is the user's primary organization. A user may only have one primary organization.
        /// </summary>
        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        /// <summary>
        /// Text string symbol of the organization. For example, the text symbol for Google is GOOG.
        /// </summary>
        [Input("symbol")]
        public Input<string>? Symbol { get; set; }

        /// <summary>
        /// The user's title within the organization. For example, member or engineer.
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// The type of organization. Acceptable values: `domain_only`, `school`, `unknown`, `work`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public UserOrganizationArgs()
        {
        }
    }
}
