// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GoogleWorkspace.Inputs
{

    public sealed class UserAddressGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Country
        /// </summary>
        [Input("country")]
        public Input<string>? Country { get; set; }

        /// <summary>
        /// The country code. Uses the ISO 3166-1 standard.
        /// </summary>
        [Input("countryCode")]
        public Input<string>? CountryCode { get; set; }

        /// <summary>
        /// If the address type is custom, this property contains the custom value.
        /// </summary>
        [Input("customType")]
        public Input<string>? CustomType { get; set; }

        /// <summary>
        /// For extended addresses, such as an address that includes a sub-region.
        /// </summary>
        [Input("extendedAddress")]
        public Input<string>? ExtendedAddress { get; set; }

        /// <summary>
        /// A full and unstructured postal address. This is not synced with the structured address fields.
        /// </summary>
        [Input("formatted")]
        public Input<string>? Formatted { get; set; }

        /// <summary>
        /// The town or city of the address.
        /// </summary>
        [Input("locality")]
        public Input<string>? Locality { get; set; }

        /// <summary>
        /// The post office box, if present.
        /// </summary>
        [Input("poBox")]
        public Input<string>? PoBox { get; set; }

        /// <summary>
        /// The ZIP or postal code, if applicable.
        /// </summary>
        [Input("postalCode")]
        public Input<string>? PostalCode { get; set; }

        /// <summary>
        /// If this is the user's primary address. The addresses list may contain only one primary address.
        /// </summary>
        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        /// <summary>
        /// The abbreviated province or state.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Indicates if the user-supplied address was formatted. Formatted addresses are not currently supported.
        /// </summary>
        [Input("sourceIsStructured")]
        public Input<bool>? SourceIsStructured { get; set; }

        /// <summary>
        /// The street address, such as 1600 Amphitheatre Parkway. Whitespace within the string is ignored; however, newlines are significant.
        /// </summary>
        [Input("streetAddress")]
        public Input<string>? StreetAddress { get; set; }

        /// <summary>
        /// The address type. Acceptable values: `custom`, `home`, `other`, `work`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public UserAddressGetArgs()
        {
        }
    }
}
