// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDomainAlias(args: GetDomainAliasArgs, opts?: pulumi.InvokeOptions): Promise<GetDomainAliasResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("googleworkspace:index/getDomainAlias:getDomainAlias", {
        "domainAliasName": args.domainAliasName,
    }, opts);
}

/**
 * A collection of arguments for invoking getDomainAlias.
 */
export interface GetDomainAliasArgs {
    /**
     * The domain alias name.
     */
    domainAliasName: string;
}

/**
 * A collection of values returned by getDomainAlias.
 */
export interface GetDomainAliasResult {
    /**
     * Creation time of the domain alias.
     */
    readonly creationTime: number;
    /**
     * The domain alias name.
     */
    readonly domainAliasName: string;
    /**
     * ETag of the resource.
     */
    readonly etag: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * The parent domain name that the domain alias is associated with. This can either be a primary or secondary domain name within a customer.
     */
    readonly parentDomainName: string;
    /**
     * Indicates the verification state of a domain alias.
     */
    readonly verified: boolean;
}

export function getDomainAliasOutput(args: GetDomainAliasOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDomainAliasResult> {
    return pulumi.output(args).apply(a => getDomainAlias(a, opts))
}

/**
 * A collection of arguments for invoking getDomainAlias.
 */
export interface GetDomainAliasOutputArgs {
    /**
     * The domain alias name.
     */
    domainAliasName: pulumi.Input<string>;
}
